
GET http://localhost:8080/volunteers

###

POST  http://localhost:8080/addTopic
Content-Type: application/json

[
    {
        "topicName" : "DSA",
        "category": "CSE"
    }
]

###

POST http://localhost:8080/saveStudentPref
Content-Type: application/json

{
    "username": "dwight",
    "topics": [
        {
            "topicName": "DSA"
        }
    ]
}