
GET http://localhost:8080/topics

###

POST  http://localhost:8080/addTopic
Content-Type: application/json

[
	{
		"topicName": "Mathematics",
		"category": "School(1-7)"
	},
	{
		"topicName": "Science",
		"category": "School(1-7)"
	},
	{
		"topicName": "Social Science",
		"category": "School(1-7)"
	},
	{
		"topicName": "English",
		"category": "School(1-7)"
	},
	{
		"topicName": "Mathematics",
		"category": "School(8-10)"
	},
	{
		"topicName": "Science",
		"category": "School(8-10)"
	},
	{
		"topicName": "Social Science",
		"category": "School(8-10)"
	},
	{
		"topicName": "English",
		"category": "School(8-10)"
	},
	{
		"topicName": "Mathematics",
		"category": "School(8-10)"
	},
	{
		"topicName": "DSA",
		"category": "CSE)"
	},
	{
		"topicName": "DBMS",
		"category": "CSE"
	},
	{
		"topicName": "Stem Cells",
		"category": "Biotechnology"
	},
	{
		"topicName": "Bio-Informatics",
		"category": "Biotechnology"
	},
	{
		"topicName": "Control Systems",
		"category": "Electronics"
	}
]

###

POST http://localhost:8080/saveStudentPref
Content-Type: application/json

{
    "username": "dwight",
    "topics": [
        {
            "topicName": "DSA"
        }
    ]
}


###

GET http://localhost:8080/meeting
